### ISSUE TITLE
SVT:zipkin user feature published in maven central not functional.

### ISSUE THREAD

**Issue by jagraj** [WASdev/sample.opentracing.zipkintracer#13]
Feature definition is missing in zipkin 1.1 user feature published to maven central.

https://github.com/WASdev/sample.opentracing.zipkintracer/releases/download/1.1/liberty-opentracing-zipkintracer-1.1-sample.zip

**Comment by fmhwong** [comment]
Resolved by uploading version 1.1.2 to Maven.
