### ISSUE TITLE
A feature definition could not be found for io.openliberty.opentracing-2.0

### ISSUE THREAD

**Issue by pugmas** [WASdev/sample.opentracing.zipkintracer#26]
Using opentracingZipkin-0.33 with Open Liberty 21.0.0.3/wlp-1.0.50.cl210320210309-1101 on Eclipse OpenJ9 VM, version 11.0.10+9

an error occurs at server start:
E CWWKF0001E: A feature definition could not be found for io.openliberty.opentracing-2.0

**Possible cause** 
https://github.com/OpenLiberty/open-liberty/commit/cb77fea657b9797fa42e38abcb598f8fa5ca70f6

**Possible solution** 
```
opentracingZipkin-0.33.mf:

- Subsystem-Content: io.opentracing-2.0; type="osgi.subsystem.feature",
+ Subsystem-Content: com.ibm.websphere.appserver.opentracing-2.0; type="osgi.subsystem.feature",
```

**Comment by fmhwong** [comment]
Fixed by https://github.com/WASdev/sample.opentracing.zipkintracer/pull/27
