### ISSUE TITLE
OpenTracing extension not yet compatible with javaee-8.0 feature

### ISSUE THREAD

**Issue by sdaschner** [WASdev/sample.opentracing.zipkintracer#7]
Hi there,

I don't know if this is repo is active, however, it's currently not possible to simple add the `usr:opentracingZipkin-0.30` feature if `javaee-8.0` is active.

Please see the logs that show the conflict there:

Reproducer: https://github.com/sdaschner/instrument-craft-shop/tree/master and change the features in `openliberty/server.xml`, Docker build and run.

```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Launching defaultServer (Open Liberty 18.0.0.1/wlp-1.0.21.20180325-1900) on OpenJDK 64-Bit Server VM, version 1.8.0_111-8u111-b14-2~bpo8+1-b14 (en)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[ERROR   ] CWWKF0033E: The singleton features servlet-3.1 and servlet-4.0 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.mail-1.5 and com.ibm.websphere.appserver.javax.mail-1.6 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features cdi-1.2 and cdi-2.0 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features jaxrs-2.0 and jaxrs-2.1 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.validation-1.1 and com.ibm.websphere.appserver.javax.validation-2.0 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.jsf-2.2 and com.ibm.websphere.appserver.javax.jsf-2.3 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.annotation-1.2 and com.ibm.websphere.appserver.javax.annotation-1.3 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.persistence-2.1 and com.ibm.websphere.appserver.javax.persistence-2.2 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javaeeCompatible-7.0 and com.ibm.websphere.appserver.javaeeCompatible-8.0 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.cdi-1.2 and com.ibm.websphere.appserver.javax.cdi-2.0 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.persistence.base-2.1 and com.ibm.websphere.appserver.javax.persistence.base-2.2 cannot be loaded at the same time.  The configured features usr:opentracingZipkin-0.30 and javaee-8.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
```

Just out of interest: I can't find any obvious dependencies to `javaee-7.0` or versions in this repository? Where does this conflict come from?

**Comment by gcharters** [comment]
Hi @sdaschner, thanks for raising the issue. MicroProfile is currently based on EE7. I believe MP 2.0 is slated to adopt EE8 spec levels. 

In terms of where the conflict comes from, the feature manifest (https://github.com/WASdev/sample.opentracing.zipkintracer/blob/master/src/features/opentracingZipkin-0.30.mf) lists opentracing-1.0 as a dependency. You can see the opentracing dependencies here:
 https://developer.ibm.com/wasdev/downloads/#asset/features-com.ibm.websphere.appserver.opentracing-1.0 and it lists EE7 features as dependencies (see the "Features that this feature enables" section).
That's from the WebSphere Liberty repo, but that feature is in Open Liberty and the feature file that defines the dependencies is:
 https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.0/com.ibm.websphere.appserver.opentracing-1.0.feature

I hope this helps. 

I'll leave others to comment on whether enabling EE8 ahead of MP 2.0 is likely to happen.

**Comment by sdaschner** [comment]
That helps indeed, thanks! So I know where to start tweaking. Yes, please keep me updated.

**Comment by gcharters** [comment]
Hi @sdaschner - it looks like the opentracing-1.0 feature tolerates the ee8 features because the .feature file mentioned in the earlier comment (I updated it to fix a missing link) contains:
-features=com.ibm.websphere.appserver.jaxrs-2.0; ibm.tolerates:=2.1, \
com.ibm.websphere.appserver.cdi-1.2; ibm.tolerates:=2.0

It should therefore be possible to add toleration to this to get it to work:
https://github.com/WASdev/sample.opentracing.zipkintracer/blob/master/src/features/opentracingZipkin-0.30.mf

If I get chance, I try to give it a go.

**Comment by gcharters** [comment]
Hi @sdaschner , I managed to get the following feature set to start:

```XML
<featureManager>
    <feature>javaee-8.0</feature>
    <feature>mpOpenTracing-1.0</feature>
     <feature>usr:opentracingZipkin-0.30</feature>
</featureManager>
```

By adding these two jaxrs/cdi entries to the `wlp/usr/extension/lib/features/opentracingZipkin-0.30.mf` feature manifest, after you've installed the zipkin feature as an extension:

Subsystem-Content: com.ibm.websphere.appserver.opentracing-1.0; type="osgi.subsystem.feature",
 com.ibm.ws.opentracing.zipkin; version="[1.0.0,1.0.200)", 
 **com.ibm.websphere.appserver.jaxrs-2.0; type="osgi.subsystem.feature"; ibm.tolerates:=2.1,
 com.ibm.websphere.appserver.cdi-1.2; type="osgi.subsystem.feature"; ibm.tolerates:=2.0**
